AzerothAdminEasy = AzerothAdminEasy or {}

AzerothAdminEasy.Categories = {
    { name = "GM메뉴", short = "GM메뉴", commands = {
        { label = "대상 즉시 처치", command = ".die", requires = "unit", hint = "선택한 플레이어/크리쳐를 즉시 처치합니다.", confirm = true, danger = true },
        { label = "부활", action = "revive", permissionCommand = ".revive", hint = "죽음/유령 상태에서는 자신을 우선 부활하고, 생존 상태에서는 선택 플레이어를 부활합니다." },
        { label = "무적 전환", action = "godToggle", hint = "현재 GM 캐릭터의 God 모드를 켜고 끕니다." },
        { label = "투명화 전환", action = "visibilityToggle", hint = "현재 GM 캐릭터의 투명 상태를 켜고 끕니다." },
        { label = "GM 날기 전환", action = "flightToggle", hint = "현재 GM 캐릭터의 비행 모드를 켜고 끕니다." },
        { label = "수면 걷기 전환", action = "waterwalkToggle", hint = "현재 GM 캐릭터의 수면 걷기 치트를 켜고 끕니다." },
        { label = "이동속도 3배 전환", action = "speedToggle", hint = "현재 GM 캐릭터의 전체 이동속도를 1배/3배로 전환합니다." },
        { label = "퀘스트 도우미", action = "questhelper", hint = "진행 중 퀘스트, 퀘스트 한글/ID 검색, 완료/위치/목표 기능을 엽니다." },
        { label = "은행 가방 열기/닫기", action = "bankToggle", hint = "AzerothCore 원격 은행 세션으로 실제 기본 은행 UI를 열고 닫습니다. 원격 확인 목록창은 사용하지 않습니다." },
        { label = "전문기술 정보", action = "craftInfo", hint = "전문기술 정보창을 엽니다. 재료 클릭=수량 입력 후 생성, 미습득 도안 클릭=GM 습득." },
        { label = "아이템 정보", action = "itemInfo", hint = "통합 아이템 획득처/분류 정보를 엽니다." },
        { label = "선택 대상 100골드", command = ".modify money 1000000", requires = "player", hint = "선택한 플레이어에게 100골드를 추가합니다." },
        { label = "선택 대상 레벨 +1", command = ".levelup 1", requires = "player", hint = "선택한 플레이어 레벨을 1 올립니다." },
        { label = "선택 대상 레벨 -1", command = ".levelup -1", requires = "player", hint = "선택한 플레이어 레벨을 1 내립니다." },
        { label = "내 직업 주문 전체", command = ".learn all my class", hint = "현재 GM 캐릭터의 직업 주문/특성/퀘스트 보상 주문을 학습합니다." },
        { label = "내 트레이너 주문 전체", command = ".learn all my trainer", hint = "현재 GM 캐릭터가 트레이너에서 배울 수 있는 주문을 모두 학습합니다." },
        { label = "숙련도 최대", command = ".maxskill", requires = "player", hint = "선택 플레이어가 보유한 숙련도를 최대치로 올립니다." },
        { label = "비행 경로 전체 해제", command = ".cheat taxi on", hint = "현재 GM 캐릭터의 모든 비행 경로를 해제합니다." },
        { label = "GPS", command = ".gps", hint = "선택 대상이 있으면 대상, 없으면 자신의 맵/좌표 정보를 출력합니다." },
        { label = "순간이동 목록", action = "teleports", hint = "기존 한글 순간이동 좌표 목록을 엽니다." },
    } },

    { name = "GM", short = "GM", commands = {
        { label = "계정 정보", command = ".account", hint = "현재 계정의 GM 보안 레벨과 계정 정보를 표시합니다." },
        { label = "온라인 계정 목록", command = ".account onlinelist", hint = "현재 접속 중인 계정/캐릭터를 표시합니다." },
        { label = "접속 중 GM", command = ".gm ingame", hint = "현재 게임에 접속 중인 GM 목록을 표시합니다." },
        { label = "GM 계정 목록", command = ".gm list", hint = "GM 계정 목록을 표시합니다." },
        { label = "GM 채팅 켜기", command = ".gm chat on", hint = "GM 채팅 표시를 켭니다." },
        { label = "GM 채팅 끄기", command = ".gm chat off", hint = "GM 채팅 표시를 끕니다." },
        { label = "관전 모드 켜기", command = ".gm spectator on", hint = "관전 모드를 켭니다." },
        { label = "관전 모드 끄기", command = ".gm spectator off", hint = "관전 모드를 끕니다." },
        { label = "귓속말 받기", command = ".whispers on", hint = "GM이 일반 플레이어의 귓속말을 받습니다." },
        { label = "귓속말 차단", command = ".whispers off", hint = "GM이 일반 플레이어의 귓속말을 받지 않습니다." },
        { label = "GM 전체 알림", command = ".gmnotify {args}", hint = "인수: 메시지", example = "예: 서버 점검을 시작합니다." },
        { label = "계정 생성", command = ".account create {args}", hint = "인수: 계정명 비밀번호", example = "예: TEST test1234", confirm = true, danger = true },
        { label = "계정 삭제", command = ".account delete {args}", hint = "인수: 계정명", example = "예: TEST", confirm = true, danger = true },
        { label = "현재 계정 IP 잠금", command = ".account lock ip on", hint = "현재 접속 계정을 현재 IP에 잠급니다.", confirm = true },
        { label = "현재 계정 IP 잠금 해제", command = ".account lock ip off", hint = "현재 접속 계정의 IP 잠금을 해제합니다.", confirm = true },
        { label = "확장팩 권한 설정", command = ".account set addon {args}", hint = "인수: 계정명 확장팩값", example = "예: TEST 2   (2 = WotLK)" },
        { label = "GM 레벨 설정", command = ".account set gmlevel {args}", hint = "인수: 계정명 GM레벨 RealmID\n선택 플레이어 사용 시: GM레벨 RealmID", example = "예: TEST 2 1\n예: TEST 2 -1 (모든 Realm)\n선택 대상: 2 1" },
        { label = "비밀번호 설정", command = ".account set password {args}", hint = "인수: 계정명 새암호 새암호", example = "예: TEST NewPass123 NewPass123", confirm = true, danger = true },
        { label = "캐릭터 계정 이동", command = ".character changeaccount {args}", hint = "인수: 새계정명 캐릭터명", example = "예: TEST Mychar", confirm = true, danger = true },
        { label = "GM 권한 재검사", action = "probeSecurity", hint = "현재 계정의 GM 보안 레벨을 .account 응답에서 자동 감지하고 권한 부족 버튼을 잠급니다." },
    } },

    { name = "캐릭터", short = "캐릭터", commands = {
        { label = "전문기술 정보", action = "craftInfo", hint = "전문기술 정보창을 엽니다." },
        { label = "플레이어 정보", command = ".pinfo", requires = "player", hint = "선택 플레이어의 계정/캐릭터 정보를 표시합니다." },
        { label = "GUID 표시", command = ".guid", requires = "player", hint = "선택한 플레이어 캐릭터의 GUID를 표시합니다. 크리쳐 GUID는 크리쳐 탭의 NPC GUID를 사용하세요." },
        { label = "거리 확인", command = ".distance", requires = "creature", hint = "선택한 크리쳐와의 거리를 표시합니다." },
        { label = "GPS", command = ".gps", hint = "선택 대상이 있으면 대상, 없으면 자신의 좌표를 표시합니다." },
        { label = "저장", command = ".save", hint = "현재 GM 캐릭터를 DB에 저장합니다." },
        { label = "리콜", command = ".recall", hint = "선택 플레이어가 있으면 그 플레이어를, 없으면 자신을 이전 Recall 위치로 이동합니다." },
        { label = "추방", command = ".kick", requires = "player", hint = "선택 플레이어를 서버에서 추방합니다.", confirm = true, danger = true },
        { label = "쿨다운 초기화", command = ".cooldown", hint = "선택 플레이어가 있으면 대상, 없으면 자신의 재사용 대기시간을 초기화합니다." },
        { label = "전투 중지", command = ".combatstop", hint = "선택 플레이어의 전투를 종료합니다. 플레이어 대상이 없으면 자신에게 적용됩니다." },
        { label = "부활", action = "revive", permissionCommand = ".revive", hint = "죽음/유령 상태에서는 자신을 우선 부활하고, 생존 상태에서는 선택 플레이어를 부활합니다." },
        { label = "메일함 열기", command = ".mailbox", hint = "현재 GM 캐릭터의 원격 메일함을 엽니다." },
        { label = "탈것 내리기", command = ".dismount", hint = "현재 GM 캐릭터의 탈것을 해제합니다." },
        { label = "동결", command = ".freeze", requires = "player", hint = "선택 플레이어를 동결합니다." },
        { label = "동결 해제", command = ".unfreeze", requires = "player", hint = "선택 플레이어의 동결을 해제합니다." },
        { label = "이름 변경 요구", command = ".character rename", requires = "player", hint = "선택 플레이어에게 다음 로그인 시 이름 변경을 요구합니다.", confirm = true },
        { label = "외형 변경 요구", command = ".character customize", requires = "player", hint = "선택 플레이어에게 외형 변경을 허용합니다.", confirm = true },
        { label = "종족 변경 요구", command = ".character changerace", requires = "player", hint = "선택 플레이어에게 종족 변경을 허용합니다.", confirm = true },
        { label = "진영 변경 요구", command = ".character changefaction", requires = "player", hint = "선택 플레이어에게 진영 변경을 허용합니다.", confirm = true },
        { label = "삭제 캐릭터 목록", command = ".character deleted list", hint = "삭제된 캐릭터 목록을 표시합니다." },
        { label = "삭제 캐릭터 복구", command = ".character deleted restore {args}", hint = "인수: GUID|이름 [새이름] [새계정]", example = "예: 12345", confirm = true },
        { label = "가방 검사", command = ".character check bag {args}", hint = "인수: [캐릭터명] 가방슬롯(1~4)", example = "예: Mychar 1\n예: 1" },
        { label = "은행 검사", command = ".character check bank", hint = "현재 GM 캐릭터의 은행 인벤토리 정보를 출력합니다." },
        { label = "전문기술 검사", command = ".character check profession", hint = "선택한 플레이어의 전문기술 목록을 출력합니다. 선택 대상이 없으면 서버 기본 동작을 사용합니다." },
        { label = "레벨 변경", command = ".levelup {args}", requires = "player", hint = "인수: 증감 레벨", example = "예: 5 또는 -5" },
        { label = "돈 변경", command = ".modify money {args}", requires = "player", hint = "인수: copper 또는 g/s/c 표기", example = "예: 1000000 또는 100g" },
        { label = "생명력 변경", command = ".modify hp {args}", requires = "player", hint = "인수: 최대/현재 생명력 값", example = "예: 50000" },
        { label = "마나 변경", command = ".modify mana {args}", requires = "player", hint = "인수: 최대/현재 마나 값", example = "예: 30000" },
        { label = "기력 변경", command = ".modify energy {args}", requires = "player", hint = "인수: 기력 값", example = "예: 100" },
        { label = "분노 변경", command = ".modify rage {args}", requires = "player", hint = "인수: 분노 값", example = "예: 100" },
        { label = "룬마력 변경", command = ".modify runicpower {args}", requires = "player", hint = "인수: 룬마력 값", example = "예: 100" },
        { label = "명예 변경", command = ".modify honor {args}", requires = "player", hint = "인수: 증감 명예 점수", example = "예: 10000" },
        { label = "투기장 점수", command = ".modify arenapoints {args}", requires = "player", hint = "인수: 증감 점수", example = "예: 1000" },
        { label = "취기 변경", command = ".modify drunk {args}", requires = "player", hint = "인수: 0~100", example = "예: 0" },
        { label = "크기 변경", command = ".modify scale {args}", requires = "unit", hint = "인수: 0.1~10.0", example = "예: 1.5" },
        { label = "성별 남성", command = ".modify gender male", requires = "player", hint = "선택 플레이어의 성별을 남성으로 변경합니다." },
        { label = "성별 여성", command = ".modify gender female", requires = "player", hint = "선택 플레이어의 성별을 여성으로 변경합니다." },
        { label = "모델 변경", command = ".morph target {args}", requires = "unit", hint = "인수: DisplayID", example = "예: 49" },
        { label = "모델 초기화", command = ".morph reset", requires = "unit", hint = "선택 대상의 Morph를 초기화합니다." },
        { label = "속도 전체 변경", command = ".modify speed all {args}", requires = "player", hint = "인수: 0.1~50", example = "예: 3" },
        { label = "페이즈 변경", command = ".modify phase {args}", requires = "player", hint = "인수: PhaseMask", example = "예: 1" },
        { label = "오라 추가", command = ".aura {args}", requires = "unit", hint = "인수: SpellID", example = "예: 12345" },
        { label = "오라 제거", command = ".unaura {args}", requires = "unit", hint = "인수: SpellID 또는 all", example = "예: all" },
        { label = "주문 습득", command = ".player learn {args}", hint = "인수: SpellID 또는 플레이어명 SpellID", example = "예: 33388\n예: Mychar 33388" },
        { label = "주문 삭제", command = ".player unlearn {args}", hint = "인수: SpellID 또는 플레이어명 SpellID", example = "예: 33388" },
    } },

    { name = "크리쳐", short = "크리쳐", commands = {
        { label = "크리쳐 한글/ID 검색", action = "kr_creature_search", hint = "koKR 한글명 또는 Entry ID로 크리쳐를 검색합니다." },
        { label = "NPC 정보", command = ".npc info", requires = "creature", hint = "선택 크리쳐의 Entry/Spawn 등 상세 정보를 표시합니다." },
        { label = "NPC GUID", command = ".npc guid", requires = "creature", hint = "선택 크리쳐의 DB Spawn GUID를 표시합니다. 일반 .guid 대신 AzerothCore .npc guid를 사용합니다." },
        { label = "NPC 근처 검색", command = ".npc near {args}", hint = "인수: 거리(선택). 빈 값 대신 거리를 입력하세요.", example = "예: 20" },
        { label = "거리 확인", command = ".distance", requires = "creature", hint = "선택 크리쳐와의 거리를 표시합니다." },
        { label = "NPC 생성", command = ".npc add {args}", hint = "인수: Creature Entry", example = "예: 68" },
        { label = "NPC 삭제", command = ".npc delete", requires = "creature", hint = "선택 크리쳐의 Spawn을 DB에서 삭제합니다.", confirm = true, danger = true },
        { label = "NPC 현재 위치로 이동", command = ".npc move", requires = "creature", hint = "선택 크리쳐 Spawn 위치를 현재 GM 위치로 이동합니다." },
        { label = "NPC 모델 변경", command = ".npc set model {args}", requires = "creature", hint = "인수: DisplayID", example = "예: 49" },
        { label = "NPC 레벨 변경", command = ".npc set level {args}", requires = "creature", hint = "인수: 레벨", example = "예: 80" },
        { label = "NPC 페이즈 변경", command = ".npc set phase {args}", requires = "creature", hint = "인수: PhaseMask", example = "예: 1" },
        { label = "NPC 이동형태", command = ".npc set movetype {args}", requires = "creature", hint = "인수: stay | random | way [nodel]", example = "예: stay" },
        { label = "NPC 배회거리", command = ".npc set wanderdistance {args}", requires = "creature", hint = "인수: 거리", example = "예: 10" },
        { label = "NPC 리스폰시간", command = ".npc set spawntime {args}", requires = "creature", hint = "인수: 초 또는 5m/1h", example = "예: 5m" },
        { label = "NPC 말하기", command = ".npc say {args}", requires = "creature", hint = "인수: 대사", example = "예: 안녕하세요" },
        { label = "NPC 외치기", command = ".npc yell {args}", requires = "creature", hint = "인수: 대사", example = "예: 전투 준비!" },
        { label = "NPC 에모트", command = ".npc playemote {args}", requires = "creature", hint = "인수: Emote ID", example = "예: 1" },
        { label = "NPC 따라오기", command = ".npc follow", requires = "creature", hint = "선택 크리쳐가 현재 GM을 따라오게 합니다." },
        { label = "NPC 따라오기 중지", command = ".npc follow stop", requires = "creature", hint = "선택 크리쳐의 Follow를 중지합니다." },
        { label = "NPC 길들이기", command = ".npc tame", requires = "creature", hint = "선택한 길들일 수 있는 크리쳐를 길들입니다." },
        { label = "NPC 처치", command = ".die", requires = "creature", hint = "선택 크리쳐를 즉시 처치합니다.", confirm = true, danger = true },
        { label = "NPC 리스폰", command = ".respawn", requires = "creature", hint = "선택 크리쳐를 리스폰합니다." },
        { label = "크리쳐 Entry 이동", command = ".go creature id {args}", hint = "인수: Creature Entry", example = "예: 68" },
        { label = "크리쳐 Spawn 이동", command = ".go creature {args}", hint = "인수: DB Spawn GUID", example = "예: 12345" },
        { label = "크리쳐 Spawn 목록", command = ".list creature {args}", hint = "인수: Creature Entry [표시개수]", example = "예: 68 10" },
        { label = "웨이포인트 새 점 추가", command = ".wp add", requires = "creature", hint = "선택 크리쳐의 현재 Path에 현재 위치를 새 웨이포인트로 추가합니다." },
        { label = "웨이포인트 Path에 추가", command = ".wp add {args}", hint = "인수: PathID", example = "예: 1001" },
        { label = "웨이포인트 로드", command = ".wp load {args}", requires = "creature", hint = "선택 크리쳐에 PathID를 로드합니다.", example = "예: 1001" },
        { label = "웨이포인트 언로드", command = ".wp unload", requires = "creature", hint = "선택 크리쳐의 웨이포인트 Path를 해제합니다." },
        { label = "웨이포인트 리로드", command = ".wp reload {args}", hint = "인수: PathID", example = "예: 1001" },
    } },

    { name = "오브젝트", short = "오브젝트", commands = {
        { label = "가까운 오브젝트 찾기", command = ".gobject target", hint = "현재 위치에서 가장 가까운 GameObject 정보를 찾습니다." },
        { label = "주변 오브젝트 목록", command = ".gobject near {args}", hint = "인수: 거리", example = "예: 20" },
        { label = "오브젝트 Entry 정보", command = ".gobject info {args}", hint = "인수: GameObject Entry", example = "예: 175124" },
        { label = "오브젝트 GUID 정보", command = ".gobject info guid {args}", hint = "인수: DB Spawn GUID", example = "예: 12345" },
        { label = "오브젝트 생성", command = ".gobject add {args}", hint = "인수: GameObject Entry [리스폰초]", example = "예: 175124" },
        { label = "임시 오브젝트 생성", command = ".gobject add temp {args}", hint = "인수: Entry [지속초]", example = "예: 175124 300" },
        { label = "오브젝트 이동", command = ".gobject move {args}", hint = "인수: DB Spawn GUID [x y z]. 좌표 생략 시 현재 위치.", example = "예: 12345" },
        { label = "오브젝트 회전", command = ".gobject turn {args}", hint = "인수: DB Spawn GUID [방향]", example = "예: 12345" },
        { label = "오브젝트 삭제", command = ".gobject delete {args}", hint = "인수: DB Spawn GUID", example = "예: 12345", confirm = true, danger = true },
        { label = "오브젝트 활성화", command = ".gobject activate {args}", hint = "인수: DB Spawn GUID", example = "예: 12345" },
        { label = "오브젝트 리스폰", command = ".gobject respawn {args}", hint = "인수: DB Spawn GUID", example = "예: 12345" },
        { label = "오브젝트 페이즈", command = ".gobject set phase {args}", hint = "인수: DB Spawn GUID PhaseMask", example = "예: 12345 1" },
        { label = "오브젝트 Entry 이동", command = ".go gameobject id {args}", hint = "인수: GameObject Entry", example = "예: 175124" },
        { label = "오브젝트 Spawn 이동", command = ".go gameobject {args}", hint = "인수: DB Spawn GUID", example = "예: 12345" },
        { label = "오브젝트 스폰 목록(50)", command = ".gobject near 50", hint = "현재 위치 반경 50 내 GameObject GUID/Entry/좌표를 출력합니다. 구형 .list object는 deprecated라 사용하지 않습니다." },
    } },

    { name = "아이템", short = "아이템", commands = {
        { label = "아이템 정보 / 한글·ID 검색", action = "itemInfo", hint = "통합 아이템 정보창을 엽니다. 던전/레이드/세트/PvP/퀘스트 분류 탐색과 koKR 한글·ID 검색을 한 창에서 사용합니다." },
        { label = "아이템 추가", command = ".additem {args}", hint = "인수: ItemID [수량]", example = "예: 6948 1" },
        { label = "아이템 세트 추가", command = ".additem set {args}", hint = "인수: ItemSet ID", example = "예: 1" },
        { label = "아이템 보유 목록", command = ".list item {args}", hint = "인수: ItemID [표시개수]", example = "예: 6948 10" },
        { label = "아이템 우편 발송", command = ".send items {args}", hint = "인수: 플레이어 \"제목\" \"본문\" itemID[:수량] ...", example = "예: Mychar \"GM\" \"지급\" 6948:1" },
        { label = "골드 우편 발송", command = ".send money {args}", hint = "인수: 플레이어 \"제목\" \"본문\" copper", example = "예: Mychar \"GM\" \"지급\" 1000000" },
        { label = "일반 우편 발송", command = ".send mail {args}", hint = "인수: 플레이어 \"제목\" \"본문\"", example = "예: Mychar \"공지\" \"내용\"" },
        { label = "아이템 복구 목록", command = ".item restore list {args}", hint = "인수: 플레이어명", example = "예: Mychar" },
    } },

    { name = "퀘스트", short = "퀘스트", action = "questhelper", commands = {} },

    { name = "순간이동", short = "순간이동", commands = {
        { label = "한글 순간이동 목록", action = "teleports", hint = "기존 한글 좌표 목록을 엽니다." },
        { label = "즐겨찾기 순간이동", action = "favorites", hint = "불사조 NPC SQL 기반 텍스트 순간이동 목록을 엽니다." },
        { label = "플레이어에게 이동", command = ".appear {target}", hint = "선택한 플레이어에게 이동합니다. 선택 대상이 없으면 이름을 묻습니다." },
        { label = "플레이어 소환", command = ".summon {target}", hint = "선택한 플레이어를 현재 위치로 소환합니다. 선택 대상이 없으면 이름을 묻습니다." },
        { label = "파티 소환", command = ".groupsummon {target}", hint = "대상 플레이어의 파티를 현재 위치로 소환합니다." },
        { label = "저장 텔레포트 이동", command = ".teleport {args}", hint = "인수: game_tele 이름", example = "예: GMIsland" },
        { label = "저장 텔레포트 추가", command = ".teleport add {args}", hint = "인수: 새 텔레포트 이름", example = "예: MySpot" },
        { label = "저장 텔레포트 삭제", command = ".teleport del {args}", hint = "인수: 텔레포트 이름", example = "예: MySpot", confirm = true },
        { label = "XYZ 이동", command = ".go xyz {args}", hint = "인수: x y z [mapId] [orientation]", example = "예: -8833 626 95 0" },
        { label = "ZoneXY 이동", command = ".go zonexy {args}", hint = "인수: x(0~100) y(0~100) [areaId]", example = "예: 50 50 1519" },
        { label = "Grid 이동", command = ".go grid {args}", hint = "인수: gridX gridY [mapId]", example = "예: 32 32 0" },
        { label = "퀘스트 시작위치", command = ".go quest starter {args}", hint = "인수: Quest ID", example = "예: 1102" },
        { label = "퀘스트 종료위치", command = ".go quest ender {args}", hint = "인수: Quest ID", example = "예: 1102" },
        { label = "묘지 이동", command = ".go graveyard {args}", hint = "인수: Graveyard ID", example = "예: 10" },
        { label = "택시노드 이동", command = ".go taxinode {args}", hint = "인수: TaxiNode ID", example = "예: 2" },
        { label = "트리거 이동", command = ".go trigger {args}", hint = "인수: AreaTrigger ID", example = "예: 45" },
        { label = "리콜 위치로 이동", command = ".recall", requires = "player", hint = "선택 플레이어를 Recall 위치로 이동합니다." },
    } },

    { name = "티켓", short = "티켓", commands = {
        { label = "티켓 목록", command = ".ticket list", hint = "열린 GM 티켓 목록을 표시합니다." },
        { label = "온라인 티켓", command = ".ticket onlinelist", hint = "온라인 플레이어의 티켓을 표시합니다." },
        { label = "티켓 보기(ID)", command = ".ticket viewid {args}", hint = "인수: Ticket ID", example = "예: 1" },
        { label = "티켓 보기(이름)", command = ".ticket viewname {args}", hint = "인수: 플레이어 이름", example = "예: Mychar" },
        { label = "티켓 완료", command = ".ticket complete {args}", hint = "인수: Ticket ID", example = "예: 1" },
        { label = "티켓 닫기", command = ".ticket close {args}", hint = "인수: Ticket ID", example = "예: 1", confirm = true },
        { label = "티켓 삭제", command = ".ticket delete {args}", hint = "인수: Ticket ID", example = "예: 1", confirm = true, danger = true },
        { label = "닫힌 티켓", command = ".ticket closedlist", hint = "닫힌 티켓 목록을 표시합니다." },
        { label = "길드 정보", command = ".guild info {args}", hint = "인수: 길드명 또는 길드 ID", example = "예: MyGuild" },
        { label = "길드 생성", command = ".guild create {args}", hint = "인수: [플레이어] \"길드명\"", example = "예: Mychar \"GM Guild\"", confirm = true },
        { label = "길드 초대", command = ".guild invite {args}", hint = "인수: 플레이어 \"길드명\"", example = "예: Mychar \"GM Guild\"" },
        { label = "길드 탈퇴/추방", command = ".guild uninvite", requires = "player", hint = "선택한 플레이어를 길드에서 제거합니다." },
        { label = "길드 삭제", command = ".guild delete {args}", hint = "인수: \"길드명\"", example = "예: \"GM Guild\"", confirm = true, danger = true },
    } },

    { name = "기타", short = "기타", commands = {
        { label = "스크린샷", action = "screenshot", hint = "GM 창을 잠시 숨기고 스크린샷을 저장합니다." },
        { label = "오라 전체 제거", command = ".unaura all", requires = "unit", hint = "선택 대상의 모든 오라를 제거합니다." },
        { label = "주문 시전", command = ".cast {args}", requires = "unit", hint = "인수: SpellID [triggered]", example = "예: 12345" },
        { label = "자기 자신에게 시전", command = ".cast self {args}", hint = "인수: SpellID [triggered]", example = "예: 12345" },
        { label = "펫 생성", command = ".pet create", requires = "creature", hint = "선택 크리쳐를 현재 캐릭터의 펫으로 생성합니다.", confirm = true },
        { label = "펫 삭제", command = ".pet delete", hint = "현재 펫을 삭제합니다.", confirm = true, danger = true },
        { label = "전문기술 전체 습득", command = ".learn all crafts", hint = "현재 GM 캐릭터의 모든 전문/보조기술 레시피를 습득하고 숙련도를 올립니다.", confirm = true },
        { label = "모든 언어 습득", command = ".learn all lang", hint = "현재 GM 캐릭터가 모든 언어를 습득합니다." },
        { label = "GM 주문 습득", command = ".learn all gm", hint = "GM 내부 주문을 습득합니다.", confirm = true },
        { label = "치트 상태", command = ".cheat status", hint = "현재 치트 상태를 출력합니다." },
        { label = "맵 탐험 켜기", command = ".cheat explore on", hint = "현재 캐릭터의 지도 탐험 치트를 켭니다." },
        { label = "맵 탐험 끄기", command = ".cheat explore off", hint = "지도 탐험 치트를 끕니다." },
        { label = "물 위 걷기 켜기", command = ".cheat waterwalk on", hint = "수면 걷기 치트를 켭니다." },
        { label = "물 위 걷기 끄기", command = ".cheat waterwalk off", hint = "수면 걷기 치트를 끕니다." },
        { label = "파워 치트 켜기", command = ".cheat power on", hint = "자원 소모 치트를 켭니다." },
        { label = "파워 치트 끄기", command = ".cheat power off", hint = "자원 소모 치트를 끕니다." },
        { label = "시전시간 치트 켜기", command = ".cheat casttime on", hint = "시전시간 치트를 켭니다." },
        { label = "시전시간 치트 끄기", command = ".cheat casttime off", hint = "시전시간 치트를 끕니다." },
        { label = "쿨다운 치트 켜기", command = ".cheat cooldown on", hint = "쿨다운 치트를 켭니다." },
        { label = "쿨다운 치트 끄기", command = ".cheat cooldown off", hint = "쿨다운 치트를 끕니다." },
    } },

    { name = "서버", short = "서버", commands = {
        { label = "서버 정보", command = ".server info", hint = "서버 상태/버전/접속 정보를 표시합니다." },
        { label = "서버 MOTD", command = ".server motd", hint = "현재 MOTD를 표시합니다." },
        { label = "MOTD 설정", command = ".server set motd {args}", hint = "인수: 새 MOTD", example = "예: 환영합니다" },
        { label = "전체 공지", command = ".announce {args}", hint = "인수: 공지 내용", example = "예: 서버 점검 10분 전입니다." },
        { label = "화면 알림", command = ".notify {args}", hint = "인수: 화면 알림 내용", example = "예: 서버 점검 안내" },
        { label = "GM 공지", command = ".gmannounce {args}", hint = "인수: GM 공지 내용" },
        { label = "GM 화면 알림", command = ".gmnotify {args}", hint = "인수: GM 화면 알림 내용" },
        { label = "스크립트 전체 리로드", command = ".reload all scripts", hint = "AzerothCore의 전체 스크립트 그룹을 리로드합니다.", confirm = true },
        { label = "Locale 전체 리로드", command = ".reload all locales", hint = "Locale 데이터를 리로드합니다.", confirm = true },
        { label = "게임텔레 리로드", command = ".reload game_tele", hint = "game_tele 데이터를 리로드합니다." },
        { label = "Config 리로드", command = ".reload config", hint = "지원되는 런타임 Config를 리로드합니다.", confirm = true },
        { label = "서버 재시작 10초", command = ".server restart 10", hint = "10초 후 WorldServer를 재시작합니다.", confirm = true, danger = true },
        { label = "재시작/종료 취소", command = ".server restart cancel", hint = "예약된 재시작/종료를 취소합니다." },
        { label = "서버 종료 10초", command = ".server shutdown 10", hint = "10초 후 WorldServer를 종료합니다.", confirm = true, danger = true },
        { label = "날씨 변경", command = ".wchange {args}", hint = "인수: 날씨종류 등급", example = "예: 1 1" },
        { label = "전체 저장", command = ".saveall", hint = "접속 중 캐릭터 정보를 저장합니다." },
        { label = "오래된 시체 정리", command = ".server corpses", hint = "맵의 오래된 시체를 정리합니다." },
    } },
}
