AzerothAdminEasy = AzerothAdminEasy or {}
local addon = AzerothAdminEasy

-- Curated navigation data for the creature browser.  This intentionally does
-- not duplicate the full creature_template/koKR catalog in KoKRSearchData.lua.
-- Instance and raid encounters are marked as restricted because their AI can
-- depend on map, instance, encounter or zone scripts at the original location.
addon.FeaturedCreatureCategories = {
    { key = "favorite", label = "★ 즐겨찾기" },
    { key = "all", label = "주요 크리처 전체" },
    { key = "raid", label = "레이드 보스" },
    { key = "raid_classic", label = "   └ 클래식", parent = "raid", expansion = "classic" },
    { key = "raid_tbc", label = "   └ 불타는 성전", parent = "raid", expansion = "tbc" },
    { key = "raid_wotlk", label = "   └ 리치 왕의 분노", parent = "raid", expansion = "wotlk" },
    { key = "dungeon", label = "던전 보스" },
    { key = "dungeon_classic", label = "   └ 클래식", parent = "dungeon", expansion = "classic" },
    { key = "dungeon_tbc", label = "   └ 불타는 성전", parent = "dungeon", expansion = "tbc" },
    { key = "dungeon_wotlk", label = "   └ 리치 왕의 분노", parent = "dungeon", expansion = "wotlk" },
    { key = "world", label = "월드 보스" },
    { key = "rare", label = "희귀·정예" },
    { key = "event", label = "이벤트 보스" },
    { key = "utility", label = "훈련·기능 NPC" },
    { key = "leader", label = "주요 NPC·지도자" },
}

addon.FeaturedCreatureExpansionLabels = {
    classic = "클래식",
    tbc = "불타는 성전",
    wotlk = "리치 왕의 분노",
}

addon.FeaturedCreatureGroupLabels = {
    raid = "레이드 보스",
    dungeon = "던전 보스",
    world = "월드 보스",
    rare = "희귀·정예",
    event = "이벤트 보스",
    utility = "훈련·기능 NPC",
    leader = "주요 NPC·지도자",
}

addon.FeaturedCreatures = {
    -- Classic raids
    { 10184, "오닉시아", "raid", "classic", "오닉시아의 둥지", true },
    { 11982, "마그마다르", "raid", "classic", "화산 심장부", true },
    { 11988, "초열의 골레마그", "raid", "classic", "화산 심장부", true },
    { 12018, "청지기 이그젝큐투스", "raid", "classic", "화산 심장부", true },
    { 12056, "남작 게돈", "raid", "classic", "화산 심장부", true },
    { 12057, "가르", "raid", "classic", "화산 심장부", true },
    { 12098, "설퍼론 사자", "raid", "classic", "화산 심장부", true },
    { 12118, "루시프론", "raid", "classic", "화산 심장부", true },
    { 12259, "게헨나스", "raid", "classic", "화산 심장부", true },
    { 12264, "샤즈라", "raid", "classic", "화산 심장부", true },
    { 11502, "라그나로스", "raid", "classic", "화산 심장부", true },
    { 11981, "플레임고르", "raid", "classic", "검은날개 둥지", true },
    { 11983, "화염아귀", "raid", "classic", "검은날개 둥지", true },
    { 12017, "용기대장 래쉬레이어", "raid", "classic", "검은날개 둥지", true },
    { 12435, "폭군 서슬송곳니", "raid", "classic", "검은날개 둥지", true },
    { 13020, "타락한 밸라스트라즈", "raid", "classic", "검은날개 둥지", true },
    { 14020, "크로마구스", "raid", "classic", "검은날개 둥지", true },
    { 14601, "에본로크", "raid", "classic", "검은날개 둥지", true },
    { 11583, "네파리안", "raid", "classic", "검은날개 둥지", true },
    { 14834, "학카르", "raid", "classic", "줄구룹", true },
    { 15275, "제왕 베크닐라쉬", "raid", "classic", "안퀴라즈 사원", true },
    { 15276, "제왕 베클로어", "raid", "classic", "안퀴라즈 사원", true },
    { 15727, "쑨", "raid", "classic", "안퀴라즈 사원", true },

    -- The Burning Crusade raids
    { 15550, "사냥꾼 어튜멘", "raid", "tbc", "카라잔", true },
    { 15687, "모로스", "raid", "tbc", "카라잔", true },
    { 16457, "고결의 여신", "raid", "tbc", "카라잔", true },
    { 15691, "전시 관리인", "raid", "tbc", "카라잔", true },
    { 15688, "테레스티안 일후프", "raid", "tbc", "카라잔", true },
    { 16524, "아란의 망령", "raid", "tbc", "카라잔", true },
    { 15689, "황천의 원령", "raid", "tbc", "카라잔", true },
    { 17225, "파멸의 어둠", "raid", "tbc", "카라잔", true },
    { 15690, "공작 말체자르", "raid", "tbc", "카라잔", true },
    { 18831, "왕중왕 마울가르", "raid", "tbc", "그룰의 둥지", true },
    { 17257, "마그테리돈", "raid", "tbc", "마그테리돈의 둥지", true },
    { 17767, "격노한 윈터칠", "raid", "tbc", "하이잘 산 전투", true },
    { 17808, "아네테론", "raid", "tbc", "하이잘 산 전투", true },
    { 17888, "카즈로갈", "raid", "tbc", "하이잘 산 전투", true },
    { 17842, "아즈갈로", "raid", "tbc", "하이잘 산 전투", true },
    { 17968, "아키몬드", "raid", "tbc", "하이잘 산 전투", true },
    { 19044, "용 학살자 그룰", "raid", "tbc", "그룰의 둥지", true },
    { 19514, "알라르", "raid", "tbc", "폭풍우 요새", true },
    { 19516, "공허의 절단기", "raid", "tbc", "폭풍우 요새", true },
    { 18805, "고위 점성술사 솔라리안", "raid", "tbc", "폭풍우 요새", true },
    { 19622, "캘타스 선스트라이더", "raid", "tbc", "폭풍우 요새", true },
    { 21213, "겅둥파도 모로그림", "raid", "tbc", "불뱀 제단", true },
    { 21214, "심연의 군주 카라드레스", "raid", "tbc", "불뱀 제단", true },
    { 21215, "눈먼 레오테라스", "raid", "tbc", "불뱀 제단", true },
    { 21216, "불안정한 히드로스", "raid", "tbc", "불뱀 제단", true },
    { 21217, "심연의 잠복꾼", "raid", "tbc", "불뱀 제단", true },
    { 21212, "여군주 바쉬", "raid", "tbc", "불뱀 제단", true },
    { 22887, "대장군 나젠투스", "raid", "tbc", "검은 사원", true },
    { 22898, "궁극의 심연", "raid", "tbc", "검은 사원", true },
    { 22841, "아카마의 망령", "raid", "tbc", "검은 사원", true },
    { 22871, "테론 고어핀드", "raid", "tbc", "검은 사원", true },
    { 22948, "구르토그 블러드보일", "raid", "tbc", "검은 사원", true },
    { 23418, "고뇌의 정수", "raid", "tbc", "검은 사원", true },
    { 22947, "대모 샤라즈", "raid", "tbc", "검은 사원", true },
    { 23426, "일리다리 의회", "raid", "tbc", "검은 사원", true },
    { 22917, "일리단 스톰레이지", "raid", "tbc", "검은 사원", true },
    { 24850, "칼렉고스", "raid", "tbc", "태양샘 고원", true },
    { 24882, "브루탈루스", "raid", "tbc", "태양샘 고원", true },
    { 25038, "지옥안개", "raid", "tbc", "태양샘 고원", true },
    { 25165, "여군주 사크로래쉬", "raid", "tbc", "태양샘 고원", true },
    { 25166, "대흑마법사 알리테스", "raid", "tbc", "태양샘 고원", true },
    { 25741, "므우루", "raid", "tbc", "태양샘 고원", true },
    { 25315, "킬제덴", "raid", "tbc", "태양샘 고원", true },

    -- Wrath of the Lich King raids
    { 15952, "맥스나", "raid", "wotlk", "낙스라마스", true },
    { 15953, "귀부인 팰리나", "raid", "wotlk", "낙스라마스", true },
    { 15956, "아눕레칸", "raid", "wotlk", "낙스라마스", true },
    { 15954, "역병술사 노스", "raid", "wotlk", "낙스라마스", true },
    { 15936, "부정의 헤이건", "raid", "wotlk", "낙스라마스", true },
    { 16011, "로데브", "raid", "wotlk", "낙스라마스", true },
    { 16061, "훈련교관 라주비어스", "raid", "wotlk", "낙스라마스", true },
    { 16060, "영혼 착취자 고딕", "raid", "wotlk", "낙스라마스", true },
    { 16063, "젤리에크 경", "raid", "wotlk", "낙스라마스", true },
    { 16028, "패치워크", "raid", "wotlk", "낙스라마스", true },
    { 15931, "그라불루스", "raid", "wotlk", "낙스라마스", true },
    { 15932, "글루스", "raid", "wotlk", "낙스라마스", true },
    { 15928, "타디우스", "raid", "wotlk", "낙스라마스", true },
    { 15989, "사피론", "raid", "wotlk", "낙스라마스", true },
    { 15990, "켈투자드", "raid", "wotlk", "낙스라마스", true },
    { 28859, "말리고스", "raid", "wotlk", "영원의 눈", true },
    { 28860, "살타리온", "raid", "wotlk", "흑요석 성소", true },
    { 33113, "거대 화염전차", "raid", "wotlk", "울두아르", true },
    { 33118, "용광로 군주 이그니스", "raid", "wotlk", "울두아르", true },
    { 33186, "칼날비늘", "raid", "wotlk", "울두아르", true },
    { 33293, "XT-002 해체자", "raid", "wotlk", "울두아르", true },
    { 32867, "강철파괴자", "raid", "wotlk", "울두아르", true },
    { 32930, "콜로간", "raid", "wotlk", "울두아르", true },
    { 33515, "아우리아야", "raid", "wotlk", "울두아르", true },
    { 32845, "호디르", "raid", "wotlk", "울두아르", true },
    { 32865, "토림", "raid", "wotlk", "울두아르", true },
    { 32906, "프레이야", "raid", "wotlk", "울두아르", true },
    { 33350, "미미론", "raid", "wotlk", "울두아르", true },
    { 33271, "장군 베작스", "raid", "wotlk", "울두아르", true },
    { 32871, "관찰자 알갈론", "raid", "wotlk", "울두아르", true },
    { 33288, "요그사론", "raid", "wotlk", "울두아르", true },
    { 34796, "꿰뚫는 자 고르목", "raid", "wotlk", "십자군의 시험장", true },
    { 34780, "군주 자락서스", "raid", "wotlk", "십자군의 시험장", true },
    { 34496, "아이디스 다크베인", "raid", "wotlk", "십자군의 시험장", true },
    { 34497, "피욜라 라이트베인", "raid", "wotlk", "십자군의 시험장", true },
    { 34564, "아눕아락", "raid", "wotlk", "십자군의 시험장", true },
    { 36597, "리치 왕", "raid", "wotlk", "얼음왕관 성채", true },
    { 36612, "군주 매로우가르", "raid", "wotlk", "얼음왕관 성채", true },
    { 36855, "여교주 데스위스퍼", "raid", "wotlk", "얼음왕관 성채", true },
    { 37813, "죽음의 인도자 사울팽", "raid", "wotlk", "얼음왕관 성채", true },
    { 36627, "썩은얼굴", "raid", "wotlk", "얼음왕관 성채", true },
    { 36626, "구린속", "raid", "wotlk", "얼음왕관 성채", true },
    { 37970, "공작 발라나르", "raid", "wotlk", "얼음왕관 성채", true },
    { 36789, "발리스리아 드림워커", "raid", "wotlk", "얼음왕관 성채", true },
    { 36678, "교수 퓨트리사이드", "raid", "wotlk", "얼음왕관 성채", true },
    { 36853, "신드라고사", "raid", "wotlk", "얼음왕관 성채", true },
    { 37955, "피의 여왕 라나텔", "raid", "wotlk", "얼음왕관 성채", true },
    { 39751, "전쟁의 아들 발타루스", "raid", "wotlk", "루비 성소", true },
    { 39746, "장군 자리스리안", "raid", "wotlk", "루비 성소", true },
    { 39747, "사비아나 레이지파이어", "raid", "wotlk", "루비 성소", true },
    { 39863, "할리온", "raid", "wotlk", "루비 성소", true },

    -- Representative dungeon bosses. Ordinary creatures remain available
    -- through the full koKR/Entry search.
    { 639, "에드윈 밴클리프", "dungeon", "classic", "죽음의 폐광", true },
    { 4275, "대마법사 아루갈", "dungeon", "classic", "그림자송곳니 성채", true },
    { 3975, "헤로드", "dungeon", "classic", "붉은십자군 수도원", true },
    { 3976, "붉은십자군 사령관 모그레인", "dungeon", "classic", "붉은십자군 수도원", true },
    { 7358, "혹한의 암네나르", "dungeon", "classic", "가시덩굴 구릉", true },
    { 5709, "에라니쿠스의 사령", "dungeon", "classic", "아탈학카르 신전", true },
    { 12201, "공주 테라드라스", "dungeon", "classic", "마라우돈", true },
    { 9019, "제왕 다그란 타우릿산", "dungeon", "classic", "검은바위 나락", true },
    { 10813, "발나자르", "dungeon", "classic", "스트라솔름", true },
    { 1853, "암흑스승 간들링", "dungeon", "classic", "스칼로맨스", true },
    { 10429, "대족장 렌드 블랙핸드", "dungeon", "classic", "검은바위 첨탑", true },
    { 10363, "사령관 드라키사스", "dungeon", "classic", "검은바위 첨탑", true },
    { 16808, "대족장 카르가스 블레이드피스트", "dungeon", "tbc", "으스러진 손의 전당", true },
    { 17942, "쿠아그미란", "dungeon", "tbc", "강제 노역소", true },
    { 17882, "검은 추적자", "dungeon", "tbc", "지하수렁", true },
    { 18373, "총독 말라다르", "dungeon", "tbc", "아키나이 납골당", true },
    { 18344, "연합왕자 샤파르", "dungeon", "tbc", "마나 무덤", true },
    { 18708, "울림", "dungeon", "tbc", "어둠의 미궁", true },
    { 17881, "아에누스", "dungeon", "tbc", "검은늪", true },
    { 17798, "장군 칼리스레쉬", "dungeon", "tbc", "증기 저장고", true },
    { 19220, "철두철미한 파탈리온", "dungeon", "tbc", "메카나르", true },
    { 17377, "파괴자 켈리단", "dungeon", "tbc", "피의 용광로", true },
    { 24664, "캘타스 선스트라이더", "dungeon", "tbc", "마법학자의 정원", true },
    { 23954, "약탈자 잉그바르", "dungeon", "wotlk", "우트가드 성채", true },
    { 26533, "말가니스", "dungeon", "wotlk", "옛 스트라솔름", true },
    { 26632, "예언자 타론자", "dungeon", "wotlk", "드락타론 성채", true },
    { 26723, "케리스트라자", "dungeon", "wotlk", "마력의 탑", true },
    { 26861, "왕 이미론", "dungeon", "wotlk", "우트가드 첨탑", true },
    { 27656, "지맥 수호자 에레고스", "dungeon", "wotlk", "마력의 눈", true },
    { 27978, "무쇠구체자 쇼니르", "dungeon", "wotlk", "돌의 전당", true },
    { 28923, "로켄", "dungeon", "wotlk", "번개의 전당", true },
    { 29120, "아눕아락", "dungeon", "wotlk", "아졸네룹", true },
    { 29306, "갈다라", "dungeon", "wotlk", "군드락", true },
    { 29311, "사자 볼라즈", "dungeon", "wotlk", "안카헤트: 고대 왕국", true },
    { 31134, "시아니고사", "dungeon", "wotlk", "보랏빛 요새", true },
    { 35451, "흑기사", "dungeon", "wotlk", "용사의 시험장", true },
    { 36502, "영혼의 포식자", "dungeon", "wotlk", "영혼의 제련소", true },
    { 36658, "스컬지군주 티라누스", "dungeon", "wotlk", "사론의 구덩이", true },

    -- Outdoor world bosses.  They are still flagged because world AI may rely
    -- on the original zone even though no instance map is involved.
    { 6109, "아주어고스", "world", "classic", "아즈샤라", true },
    { 12397, "군주 카자크", "world", "classic", "저주받은 땅", true },
    { 14887, "이손드레", "world", "classic", "에메랄드의 꿈 차원문", true },
    { 14888, "레손", "world", "classic", "에메랄드의 꿈 차원문", true },
    { 14889, "에메리스", "world", "classic", "에메랄드의 꿈 차원문", true },
    { 14890, "타에라", "world", "classic", "에메랄드의 꿈 차원문", true },
    { 17711, "파멸의 절단기", "world", "tbc", "어둠달 골짜기", true },
    { 18728, "파멸의 군주 카자크", "world", "tbc", "지옥불 반도", true },

    -- Notable outdoor rares and event encounters.
    { 32481, "아오토나", "rare", "wotlk", "숄라자르 분지", true },
    { 32485, "왕 크루쉬", "rare", "wotlk", "숄라자르 분지", true },
    { 32487, "고대의 퓨트리두스", "rare", "wotlk", "얼음왕관", true },
    { 32491, "잃어버린 시간의 원시비룡", "rare", "wotlk", "폭풍우 봉우리", true },
    { 32500, "더키", "rare", "wotlk", "폭풍우 봉우리", true },
    { 32517, "로크나하크", "rare", "wotlk", "숄라자르 분지", true },
    { 32630, "바이라고사", "rare", "wotlk", "폭풍우 봉우리", true },
    { 35189, "스콜", "rare", "wotlk", "폭풍우 봉우리", true },
    { 23682, "저주받은 기사", "event", "tbc", "붉은십자군 수도원", true },
    { 23872, "코렌 다이어브루", "event", "tbc", "검은바위 나락", true },
    { 25740, "아훈", "event", "tbc", "강제 노역소", true },

    -- Safe utility entries that are useful for GM testing.
    { 31144, "거장의 훈련용 허수아비", "utility", "wotlk", "주요 도시", false },
    { 31146, "영웅의 훈련용 허수아비", "utility", "wotlk", "주요 도시", false },
    { 32666, "전문가의 훈련용 허수아비", "utility", "wotlk", "주요 도시", false },
    { 32667, "숙련자의 훈련용 허수아비", "utility", "wotlk", "주요 도시", false },

    -- Major city and story NPCs.  These do not receive an automatic
    -- region-script warning, but permanent creation still requires confirmation.
    { 3057, "케른 블러드후프", "leader", "classic", "썬더 블러프", false },
    { 4949, "스랄", "leader", "classic", "오그리마", false },
    { 4968, "여군주 제이나 프라우드무어", "leader", "classic", "테라모어 섬", false },
    { 7937, "땜장이왕 멕카토크", "leader", "classic", "아이언포지", false },
    { 7999, "티란데 위스퍼윈드", "leader", "classic", "다르나서스", false },
    { 10181, "여군주 실바나스 윈드러너", "leader", "classic", "언더시티", false },
    { 16802, "로르테마르 테론", "leader", "tbc", "실버문", false },
    { 17468, "예언자 벨렌", "leader", "tbc", "엑소다르", false },
    { 29611, "국왕 바리안 린", "leader", "wotlk", "스톰윈드", false },
}
