AzerothAdminEasy = AzerothAdminEasy or {}
local addon = AzerothAdminEasy

-- Expanded boss catalog for WotLK 3.3.5a / AzerothCore.
-- Creature entry IDs are based on AzerothCore instance_encounters and raid data.
-- Keep this additive so the original curated FeaturedCreatures.lua remains intact.

local EXTRA_INSTANCE_BOSSES = {
    -- Classic: The Deadmines
    { 644, "라크조르", "dungeon", "classic", "죽음의 폐광", true },
    { 643, "스니드", "dungeon", "classic", "죽음의 폐광", true },
    { 1763, "길니드", "dungeon", "classic", "죽음의 폐광", true },
    { 646, "미스터 스마이트", "dungeon", "classic", "죽음의 폐광", true },
    { 645, "쿠키", "dungeon", "classic", "죽음의 폐광", true },
    { 647, "선장 그린스킨", "dungeon", "classic", "죽음의 폐광", true },
    { 639, "에드윈 밴클리프", "dungeon", "classic", "죽음의 폐광", true },

    -- Classic: Blackfathom Deeps
    { 4887, "가무라", "dungeon", "classic", "검은심연 나락", true },
    { 4831, "여왕 사레베스", "dungeon", "classic", "검은심연 나락", true },
    { 6243, "겔리하스트", "dungeon", "classic", "검은심연 나락", true },
    { 12902, "로구스 제트", "dungeon", "classic", "검은심연 나락", true },
    { 4830, "늙은 세라키스", "dungeon", "classic", "검은심연 나락", true },
    { 4832, "황혼의 군주 켈리스", "dungeon", "classic", "검은심연 나락", true },
    { 4829, "아쿠마이", "dungeon", "classic", "검은심연 나락", true },

    -- Classic: Blackrock Depths
    { 9018, "대심문관 게르스탄", "dungeon", "classic", "검은바위 나락", true },
    { 9025, "불의군주 록코르", "dungeon", "classic", "검은바위 나락", true },
    { 9319, "사냥개조련사 그렙마르", "dungeon", "classic", "검은바위 나락", true },
    { 9024, "화염술사 로어그레인", "dungeon", "classic", "검은바위 나락", true },
    { 9017, "불의군주 인센디우스", "dungeon", "classic", "검은바위 나락", true },
    { 9041, "문지기 스틸기스", "dungeon", "classic", "검은바위 나락", true },
    { 9056, "파이너스 다크바이어", "dungeon", "classic", "검은바위 나락", true },
    { 9016, "밸가르", "dungeon", "classic", "검은바위 나락", true },
    { 9033, "사령관 앵거포지", "dungeon", "classic", "검은바위 나락", true },
    { 8983, "골렘 군주 아젤마크", "dungeon", "classic", "검은바위 나락", true },
    { 9537, "헐레이 블랙브레스", "dungeon", "classic", "검은바위 나락", true },
    { 9502, "팔란스", "dungeon", "classic", "검은바위 나락", true },
    { 9543, "리블리 스크류스피곳", "dungeon", "classic", "검은바위 나락", true },
    { 9499, "플러거 스파즈링", "dungeon", "classic", "검은바위 나락", true },
    { 9156, "사자 화염채찍", "dungeon", "classic", "검은바위 나락", true },
    { 9035, "격노의 문지기", "dungeon", "classic", "검은바위 나락", true },
    { 9938, "마그무스", "dungeon", "classic", "검은바위 나락", true },
    { 9019, "제왕 다그란 타우릿산", "dungeon", "classic", "검은바위 나락", true },

    -- Classic: Lower/Upper Blackrock Spire
    { 9196, "대군주 오모크", "dungeon", "classic", "검은바위 첨탑", true },
    { 9236, "어둠사냥꾼 보쉬가진", "dungeon", "classic", "검은바위 첨탑", true },
    { 9237, "대장군 부네", "dungeon", "classic", "검은바위 첨탑", true },
    { 10596, "여왕 불그물거미", "dungeon", "classic", "검은바위 첨탑", true },
    { 10584, "우로크 둠하울", "dungeon", "classic", "검은바위 첨탑", true },
    { 9736, "병참장교 지그리스", "dungeon", "classic", "검은바위 첨탑", true },
    { 10268, "흉포한 기즈룰", "dungeon", "classic", "검은바위 첨탑", true },
    { 10220, "할리콘", "dungeon", "classic", "검은바위 첨탑", true },
    { 9568, "대군주 웜타라크", "dungeon", "classic", "검은바위 첨탑", true },
    { 9816, "불의수호자 엠버시어", "dungeon", "classic", "검은바위 첨탑", true },
    { 10264, "화염고리 솔라카르", "dungeon", "classic", "검은바위 첨탑", true },
    { 10429, "대족장 렌드 블랙핸드", "dungeon", "classic", "검은바위 첨탑", true },
    { 10430, "괴수", "dungeon", "classic", "검은바위 첨탑", true },
    { 10363, "사령관 드라키사스", "dungeon", "classic", "검은바위 첨탑", true },

    -- Classic: Dire Maul
    { 11490, "제브림 쏜후프", "dungeon", "classic", "혈투의 전장", true },
    { 13280, "히드로스폰", "dungeon", "classic", "혈투의 전장", true },
    { 14327, "레스텐드리스", "dungeon", "classic", "혈투의 전장", true },
    { 11492, "칼날바람 알진", "dungeon", "classic", "혈투의 전장", true },
    { 11488, "일샨나 레이븐오크", "dungeon", "classic", "혈투의 전장", true },
    { 11487, "마법학자 칼렌드리스", "dungeon", "classic", "혈투의 전장", true },
    { 11496, "이몰타르", "dungeon", "classic", "혈투의 전장", true },
    { 11489, "굽이나무 텐드리스", "dungeon", "classic", "혈투의 전장", true },
    { 11486, "왕자 토르텔드린", "dungeon", "classic", "혈투의 전장", true },
    { 14326, "경비병 몰다르", "dungeon", "classic", "혈투의 전장", true },
    { 14322, "천둥발 크리그", "dungeon", "classic", "혈투의 전장", true },
    { 14321, "경비병 펜구스", "dungeon", "classic", "혈투의 전장", true },
    { 14323, "경비병 슬립킥", "dungeon", "classic", "혈투의 전장", true },
    { 14325, "대장 크롬크러쉬", "dungeon", "classic", "혈투의 전장", true },
    { 14324, "정찰병 초루쉬", "dungeon", "classic", "혈투의 전장", true },
    { 11501, "왕 고르독", "dungeon", "classic", "혈투의 전장", true },

    -- Classic: Gnomeregan / Maraudon
    { 7079, "방사성 폐기물", "dungeon", "classic", "놈리건", true },
    { 7361, "그루비스", "dungeon", "classic", "놈리건", true },
    { 6235, "기계화 문지기 6000", "dungeon", "classic", "놈리건", true },
    { 6229, "고철 압축기 9-60", "dungeon", "classic", "놈리건", true },
    { 7800, "기계박사 텔마플러그", "dungeon", "classic", "놈리건", true },
    { 13282, "녹시온", "dungeon", "classic", "마라우돈", true },
    { 12258, "칼날채찍", "dungeon", "classic", "마라우돈", true },
    { 12236, "군주 바일텅", "dungeon", "classic", "마라우돈", true },
    { 12225, "저주받은 셀레브라스", "dungeon", "classic", "마라우돈", true },
    { 12203, "산사태", "dungeon", "classic", "마라우돈", true },
    { 13601, "땜장이 기즐록", "dungeon", "classic", "마라우돈", true },
    { 13596, "썩은아귀", "dungeon", "classic", "마라우돈", true },
    { 12201, "공주 테라드라스", "dungeon", "classic", "마라우돈", true },

    -- Classic: Ragefire / Razorfen
    { 11517, "오글플린트", "dungeon", "classic", "성난불길 협곡", true },
    { 11520, "욕망의 타라가만", "dungeon", "classic", "성난불길 협곡", true },
    { 11518, "기원사 제로쉬", "dungeon", "classic", "성난불길 협곡", true },
    { 11519, "바잘란", "dungeon", "classic", "성난불길 협곡", true },
    { 7355, "투텐카쉬", "dungeon", "classic", "가시덩굴 구릉", true },
    { 7357, "불꽃눈 모드레쉬", "dungeon", "classic", "가시덩굴 구릉", true },
    { 8567, "게걸먹보", "dungeon", "classic", "가시덩굴 구릉", true },
    { 7358, "혹한의 암네나르", "dungeon", "classic", "가시덩굴 구릉", true },
    { 6168, "루구그", "dungeon", "classic", "가시덩굴 우리", true },
    { 4424, "저주의가시 아겜", "dungeon", "classic", "가시덩굴 우리", true },
    { 4428, "죽음의예언자 잘그바", "dungeon", "classic", "가시덩굴 우리", true },
    { 4420, "대군주 램터스크", "dungeon", "classic", "가시덩굴 우리", true },
    { 4421, "서슬깃 차를가", "dungeon", "classic", "가시덩굴 우리", true },

    -- Classic: Scarlet Monastery / Scholomance
    { 3983, "심문관 비샤스", "dungeon", "classic", "붉은십자군 수도원", true },
    { 4543, "혈법사 탈노스", "dungeon", "classic", "붉은십자군 수도원", true },
    { 3974, "사냥개조련사 록시", "dungeon", "classic", "붉은십자군 수도원", true },
    { 6487, "신비술사 도안", "dungeon", "classic", "붉은십자군 수도원", true },
    { 3975, "헤로드", "dungeon", "classic", "붉은십자군 수도원", true },
    { 4542, "종교재판관 페어뱅크스", "dungeon", "classic", "붉은십자군 수도원", true },
    { 3977, "종교재판관 화이트메인", "dungeon", "classic", "붉은십자군 수도원", true },
    { 10506, "사자 키르토노스", "dungeon", "classic", "스칼로맨스", true },
    { 10503, "잔다이스 바로브", "dungeon", "classic", "스칼로맨스", true },
    { 11622, "들창어금니", "dungeon", "classic", "스칼로맨스", true },
    { 10433, "마르두크 블랙풀", "dungeon", "classic", "스칼로맨스", true },
    { 10432, "벡투스", "dungeon", "classic", "스칼로맨스", true },
    { 10508, "라스 프로스트위스퍼", "dungeon", "classic", "스칼로맨스", true },
    { 10505, "조교 말리시아", "dungeon", "classic", "스칼로맨스", true },
    { 11261, "학자 테올렌 크라스티노브", "dungeon", "classic", "스칼로맨스", true },
    { 10901, "현자 폴켈트", "dungeon", "classic", "스칼로맨스", true },
    { 10507, "라베니안", "dungeon", "classic", "스칼로맨스", true },
    { 10504, "군주 알렉세이 바로브", "dungeon", "classic", "스칼로맨스", true },
    { 10502, "여군주 일루시아 바로브", "dungeon", "classic", "스칼로맨스", true },
    { 1853, "암흑스승 간들링", "dungeon", "classic", "스칼로맨스", true },

    -- Classic: Shadowfang / Stratholme
    { 3914, "레실고어", "dungeon", "classic", "그림자송곳니 성채", true },
    { 3886, "도살자 칼날발톱", "dungeon", "classic", "그림자송곳니 성채", true },
    { 3887, "남작 실버레인", "dungeon", "classic", "그림자송곳니 성채", true },
    { 4278, "사령관 스프링베일", "dungeon", "classic", "그림자송곳니 성채", true },
    { 4279, "눈먼감시자 오도", "dungeon", "classic", "그림자송곳니 성채", true },
    { 4274, "파멸의 펜루스", "dungeon", "classic", "그림자송곳니 성채", true },
    { 3927, "늑대왕 난도스", "dungeon", "classic", "그림자송곳니 성채", true },
    { 4275, "대마법사 아루갈", "dungeon", "classic", "그림자송곳니 성채", true },
    { 10516, "용서받지 못한 자", "dungeon", "classic", "스트라솔름", true },
    { 10558, "하스싱어 포레스턴", "dungeon", "classic", "스트라솔름", true },
    { 10808, "잔혹한 티미", "dungeon", "classic", "스트라솔름", true },
    { 10997, "포병대장 윌리", "dungeon", "classic", "스트라솔름", true },
    { 11032, "광신자 말로", "dungeon", "classic", "스트라솔름", true },
    { 10811, "기록관 갈포드", "dungeon", "classic", "스트라솔름", true },
    { 10813, "발나자르", "dungeon", "classic", "스트라솔름", true },
    { 10436, "남작부인 아나스타리", "dungeon", "classic", "스트라솔름", true },
    { 10437, "네룹엔칸", "dungeon", "classic", "스트라솔름", true },
    { 10438, "냉혈한 말레키", "dungeon", "classic", "스트라솔름", true },
    { 10435, "집정관 발실라스", "dungeon", "classic", "스트라솔름", true },
    { 10439, "먹보 람스타인", "dungeon", "classic", "스트라솔름", true },
    { 10440, "남작 리븐데어", "dungeon", "classic", "스트라솔름", true },

    -- Classic: Sunken Temple / Stockades / Uldaman
    { 8580, "아탈알라리온", "dungeon", "classic", "아탈학카르 신전", true },
    { 5721, "드림사이드", "dungeon", "classic", "아탈학카르 신전", true },
    { 5720, "위버", "dungeon", "classic", "아탈학카르 신전", true },
    { 5710, "예언자 잠말란", "dungeon", "classic", "아탈학카르 신전", true },
    { 5719, "몰파즈", "dungeon", "classic", "아탈학카르 신전", true },
    { 5722, "하자스", "dungeon", "classic", "아탈학카르 신전", true },
    { 8443, "학카르의 화신", "dungeon", "classic", "아탈학카르 신전", true },
    { 5709, "에라니쿠스의 사령", "dungeon", "classic", "아탈학카르 신전", true },
    { 1696, "흉악범 타고르", "dungeon", "classic", "스톰윈드 지하감옥", true },
    { 1666, "캄 딥퓨리", "dungeon", "classic", "스톰윈드 지하감옥", true },
    { 1717, "햄혹", "dungeon", "classic", "스톰윈드 지하감옥", true },
    { 1716, "바질 스레드", "dungeon", "classic", "스톰윈드 지하감옥", true },
    { 1663, "덱스트렌 워드", "dungeon", "classic", "스톰윈드 지하감옥", true },
    { 6910, "레벨로쉬", "dungeon", "classic", "울다만", true },
    { 6906, "밸로그", "dungeon", "classic", "울다만", true },
    { 7228, "아이로나야", "dungeon", "classic", "울다만", true },
    { 7206, "고대 바위 문지기", "dungeon", "classic", "울다만", true },
    { 7291, "갈간 파이어해머", "dungeon", "classic", "울다만", true },
    { 4854, "그림로크", "dungeon", "classic", "울다만", true },
    { 2748, "아카에다스", "dungeon", "classic", "울다만", true },

    -- Classic: Wailing Caverns / Zul'Farrak
    { 3671, "여군주 아나콘드라", "dungeon", "classic", "통곡의 동굴", true },
    { 3669, "군주 코브란", "dungeon", "classic", "통곡의 동굴", true },
    { 3653, "크레쉬", "dungeon", "classic", "통곡의 동굴", true },
    { 3670, "군주 피타스", "dungeon", "classic", "통곡의 동굴", true },
    { 3674, "스컴", "dungeon", "classic", "통곡의 동굴", true },
    { 3673, "군주 서펜티스", "dungeon", "classic", "통곡의 동굴", true },
    { 5775, "영생의 베르단", "dungeon", "classic", "통곡의 동굴", true },
    { 3654, "걸신들린 무타누스", "dungeon", "classic", "통곡의 동굴", true },
    { 7795, "유체술사 벨라타", "dungeon", "classic", "줄파락", true },
    { 7273, "가즈릴라", "dungeon", "classic", "줄파락", true },
    { 8127, "안투술", "dungeon", "classic", "줄파락", true },
    { 7272, "순교자 데카", "dungeon", "classic", "줄파락", true },
    { 7271, "의술사 줌라", "dungeon", "classic", "줄파락", true },
    { 7796, "네크룸 거트츄어", "dungeon", "classic", "줄파락", true },
    { 7275, "어둠의사제 세즈지즈", "dungeon", "classic", "줄파락", true },
    { 7267, "족장 우코르즈 샌드스칼프", "dungeon", "classic", "줄파락", true },

    -- Classic raids missing from the original curated set
    { 14517, "대여사제 제클릭", "raid", "classic", "줄구룹", true },
    { 14507, "대사제 베녹시스", "raid", "classic", "줄구룹", true },
    { 14510, "대여사제 말리", "raid", "classic", "줄구룹", true },
    { 14509, "대사제 데칼", "raid", "classic", "줄구룹", true },
    { 14515, "대여사제 알로크", "raid", "classic", "줄구룹", true },
    { 11382, "혈군주 만도키르", "raid", "classic", "줄구룹", true },
    { 11380, "주술사 진도", "raid", "classic", "줄구룹", true },
    { 15348, "쿠린낙스", "raid", "classic", "안퀴라즈 폐허", true },
    { 15341, "장군 라작스", "raid", "classic", "안퀴라즈 폐허", true },
    { 15340, "모암", "raid", "classic", "안퀴라즈 폐허", true },
    { 15370, "먹보 부루", "raid", "classic", "안퀴라즈 폐허", true },
    { 15369, "사냥꾼 아야미스", "raid", "classic", "안퀴라즈 폐허", true },
    { 15339, "무적의 오시리안", "raid", "classic", "안퀴라즈 폐허", true },
    { 15263, "예언자 스케람", "raid", "classic", "안퀴라즈 사원", true },
    { 15516, "전투감시병 살투라", "raid", "classic", "안퀴라즈 사원", true },
    { 15510, "불굴의 판크리스", "raid", "classic", "안퀴라즈 사원", true },
    { 15299, "비시두스", "raid", "classic", "안퀴라즈 사원", true },
    { 15509, "공주 후후란", "raid", "classic", "안퀴라즈 사원", true },
    { 15517, "아우로", "raid", "classic", "안퀴라즈 사원", true },

    -- The Burning Crusade dungeons
    { 18371, "죽음의 감시인 쉴라크", "dungeon", "tbc", "아키나이 납골당", true },
    { 18373, "총독 말라다르", "dungeon", "tbc", "아키나이 납골당", true },
    { 18341, "팬더모니우스", "dungeon", "tbc", "마나 무덤", true },
    { 18343, "타바로크", "dungeon", "tbc", "마나 무덤", true },
    { 18344, "연합왕자 샤파르", "dungeon", "tbc", "마나 무덤", true },
    { 22930, "요르", "dungeon", "tbc", "마나 무덤", true },
    { 18472, "흑마술사 시스", "dungeon", "tbc", "세데크 전당", true },
    { 18473, "갈퀴대왕 이키스", "dungeon", "tbc", "세데크 전당", true },
    { 23035, "안주", "dungeon", "tbc", "세데크 전당", true },
    { 18731, "사자 지옥아귀", "dungeon", "tbc", "어둠의 미궁", true },
    { 18667, "선동자 검은심장", "dungeon", "tbc", "어둠의 미궁", true },
    { 18732, "단장 보르필", "dungeon", "tbc", "어둠의 미궁", true },
    { 18708, "울림", "dungeon", "tbc", "어둠의 미궁", true },
    { 17941, "배반자 멘누", "dungeon", "tbc", "강제 노역소", true },
    { 17991, "딱딱이 로크마르", "dungeon", "tbc", "강제 노역소", true },
    { 17942, "쿠아그미란", "dungeon", "tbc", "강제 노역소", true },
    { 17797, "풍수사 세스피아", "dungeon", "tbc", "증기 저장고", true },
    { 17796, "기계박사 스팀리거", "dungeon", "tbc", "증기 저장고", true },
    { 17798, "장군 칼리스레쉬", "dungeon", "tbc", "증기 저장고", true },
    { 17770, "헝가르펜", "dungeon", "tbc", "지하수렁", true },
    { 18105, "가즈안", "dungeon", "tbc", "지하수렁", true },
    { 17826, "늪군주 뮤즐레크", "dungeon", "tbc", "지하수렁", true },
    { 17882, "검은 추적자", "dungeon", "tbc", "지하수렁", true },
    { 17306, "감시자 가르골마르", "dungeon", "tbc", "지옥불 성루", true },
    { 17308, "무적의 오모르", "dungeon", "tbc", "지옥불 성루", true },
    { 17537, "바즈루덴", "dungeon", "tbc", "지옥불 성루", true },
    { 17381, "재앙의 창조자", "dungeon", "tbc", "피의 용광로", true },
    { 17380, "브로고크", "dungeon", "tbc", "피의 용광로", true },
    { 17377, "파괴자 켈리단", "dungeon", "tbc", "피의 용광로", true },
    { 16807, "대흑마법사 네더쿠르스", "dungeon", "tbc", "으스러진 손의 전당", true },
    { 20923, "혈투사 포룽", "dungeon", "tbc", "으스러진 손의 전당", true },
    { 16809, "돌격대장 오므로그", "dungeon", "tbc", "으스러진 손의 전당", true },
    { 16808, "대족장 카르가스 블레이드피스트", "dungeon", "tbc", "으스러진 손의 전당", true },
    { 24723, "셀린 파이어하트", "dungeon", "tbc", "마법학자의 정원", true },
    { 24744, "벡살루스", "dungeon", "tbc", "마법학자의 정원", true },
    { 24560, "여사제 델리사", "dungeon", "tbc", "마법학자의 정원", true },
    { 24664, "캘타스 선스트라이더", "dungeon", "tbc", "마법학자의 정원", true },
    { 17848, "부관 드레이크", "dungeon", "tbc", "옛 힐스브래드 구릉지", true },
    { 17862, "경비대장 스칼록", "dungeon", "tbc", "옛 힐스브래드 구릉지", true },
    { 18096, "시대의 사냥꾼", "dungeon", "tbc", "옛 힐스브래드 구릉지", true },
    { 17879, "시간의 군주 데자", "dungeon", "tbc", "검은늪", true },
    { 17880, "템퍼루스", "dungeon", "tbc", "검은늪", true },
    { 17881, "아에누스", "dungeon", "tbc", "검은늪", true },
    { 20870, "속박이 풀린 제레케스", "dungeon", "tbc", "알카트라즈", true },
    { 20885, "파멸의 예언자 달리아", "dungeon", "tbc", "알카트라즈", true },
    { 20886, "격노의 점술사 소코드라테스", "dungeon", "tbc", "알카트라즈", true },
    { 20912, "선구자 스키리스", "dungeon", "tbc", "알카트라즈", true },
    { 17976, "지휘관 새래니스", "dungeon", "tbc", "신록의 정원", true },
    { 17975, "고위 식물학자 프레이윈", "dungeon", "tbc", "신록의 정원", true },
    { 17978, "감시인 쏜그린", "dungeon", "tbc", "신록의 정원", true },
    { 17980, "라즈", "dungeon", "tbc", "신록의 정원", true },
    { 17977, "차원의 분리자", "dungeon", "tbc", "신록의 정원", true },
    { 19219, "기계군주 캐퍼시투스", "dungeon", "tbc", "메카나르", true },
    { 19221, "황천술사 세페스레아", "dungeon", "tbc", "메카나르", true },
    { 19220, "철두철미한 파탈리온", "dungeon", "tbc", "메카나르", true },

    -- The Burning Crusade: Zul'Aman
    { 23574, "아킬존", "raid", "tbc", "줄아만", true },
    { 23576, "날로라크", "raid", "tbc", "줄아만", true },
    { 23578, "잔알라이", "raid", "tbc", "줄아만", true },
    { 23577, "할라지", "raid", "tbc", "줄아만", true },
    { 24239, "주술 군주 말라크라스", "raid", "tbc", "줄아만", true },
    { 23863, "줄진", "raid", "tbc", "줄아만", true },

    -- Wrath: Gundrak boss omitted from the original curated set
    { 29307, "드라카리 거대골렘", "dungeon", "wotlk", "군드락", true },

    -- Wrath: Vault of Archavon, absent from the original curated set
    { 31125, "바위 감시자 아카본", "raid", "wotlk", "아카본 석실", true },
    { 33993, "폭풍 감시자 에말론", "raid", "wotlk", "아카본 석실", true },
    { 35013, "화염 감시자 코랄론", "raid", "wotlk", "아카본 석실", true },
    { 38433, "얼음 감시자 토라본", "raid", "wotlk", "아카본 석실", true },
}

local function appendMissing(list)
    addon.FeaturedCreatures = addon.FeaturedCreatures or {}
    local known = {}
    local i
    for i = 1, table.getn(addon.FeaturedCreatures) do
        local entry = tonumber(addon.FeaturedCreatures[i] and addon.FeaturedCreatures[i][1])
        if entry then known[entry] = true end
    end
    for i = 1, table.getn(list) do
        local record = list[i]
        local entry = tonumber(record and record[1])
        if entry and not known[entry] then
            table.insert(addon.FeaturedCreatures, record)
            known[entry] = true
        end
    end
end

appendMissing(EXTRA_INSTANCE_BOSSES)
