#!/usr/bin/env python3
"""Generate WotLK quest reward buckets from AzerothCore and AreaTable.dbc."""

from __future__ import annotations

import argparse
import csv
import hashlib
import struct
from pathlib import Path


FIXED_ITEM_COLUMNS = (22, 24, 26, 28)
CHOICE_ITEM_COLUMNS = (38, 40, 42, 44, 46, 48)
MAP_TO_BUCKET = {571: "z1", 530: "z2", 1: "z3", 0: "z4"}
MAX_WOTLK_ITEM_ID = 56806


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def parse_area_dbc(payload: bytes) -> dict[int, int]:
    if len(payload) < 20 or payload[:4] != b"WDBC":
        raise ValueError("AreaTable.dbc is not a WDBC file")
    record_count, field_count, record_size, string_size = struct.unpack(
        "<4I", payload[4:20]
    )
    if record_size != field_count * 4:
        raise ValueError("AreaTable.dbc record size does not match its fields")
    expected_size = 20 + record_count * record_size + string_size
    if len(payload) < expected_size:
        raise ValueError("AreaTable.dbc is truncated")

    areas: dict[int, int] = {}
    row_format = "<" + "I" * field_count
    for index in range(record_count):
        start = 20 + index * record_size
        row = struct.unpack(row_format, payload[start : start + record_size])
        areas[row[0]] = row[1]
    return areas


def parse_quest_sql(text: str) -> list[list[str]]:
    rows: list[list[str]] = []
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line.startswith("("):
            continue
        if not (line.endswith("),") or line.endswith(");")):
            raise ValueError("unexpected quest_template value row ending")
        row = next(
            csv.reader(
                [line[1:-2]], delimiter=",", quotechar="'", escapechar="\\"
            )
        )
        if len(row) <= CHOICE_ITEM_COLUMNS[-1]:
            raise ValueError("quest_template row has too few columns")
        rows.append(row)
    if not rows:
        raise ValueError("quest_template SQL contains no value rows")
    return rows


def build_buckets(
    rows: list[list[str]], area_maps: dict[int, int]
) -> dict[str, dict[str, set[int]]]:
    buckets = {
        name: {"fixed": set(), "choice": set()}
        for name in MAP_TO_BUCKET.values()
    }
    for row in rows:
        quest_sort = int(row[4])
        bucket_name = MAP_TO_BUCKET.get(area_maps.get(quest_sort))
        if not bucket_name:
            continue
        for kind, columns in (
            ("fixed", FIXED_ITEM_COLUMNS),
            ("choice", CHOICE_ITEM_COLUMNS),
        ):
            for column in columns:
                item_id = int(row[column])
                if 0 < item_id <= MAX_WOTLK_ITEM_ID:
                    buckets[bucket_name][kind].add(item_id)
    return buckets


def render_numbers(values: set[int], indent: str = "      ") -> list[str]:
    ordered = sorted(values)
    if not ordered:
        return [indent]
    return [
        indent + ",".join(str(value) for value in ordered[start : start + 16]) + ","
        for start in range(0, len(ordered), 16)
    ]


def render_lua(
    buckets: dict[str, dict[str, set[int]]],
    upstream_commit: str,
    quest_hash: str,
    dbc_hash: str,
) -> str:
    lines = [
        "-- Generated by tools/generate_quest_reward_335.py. Do not edit by hand.",
        "-- Includes both fixed RewardItem and selectable RewardChoiceItem rows.",
        "BlueItemInfo3QuestRewards335 = {",
        "  source = {",
        f'    upstreamCommit = "{upstream_commit}",',
        f'    questTemplateSHA256 = "{quest_hash}",',
        f'    areaTableSHA256 = "{dbc_hash}",',
        "  },",
    ]
    for bucket_name in ("z1", "z2", "z3", "z4"):
        lines.append(f"  {bucket_name} = {{")
        for kind in ("fixed", "choice"):
            lines.append(f"    {kind} = {{")
            lines.extend(render_numbers(buckets[bucket_name][kind]))
            lines.append("    },")
        lines.append("  },")
    lines.extend(("}", ""))
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--quest-sql", type=Path, required=True)
    parser.add_argument("--area-dbc", type=Path, required=True)
    parser.add_argument("--upstream-commit", required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    rows = parse_quest_sql(args.quest_sql.read_text(encoding="utf-8"))
    area_maps = parse_area_dbc(args.area_dbc.read_bytes())
    buckets = build_buckets(rows, area_maps)
    output = render_lua(
        buckets,
        args.upstream_commit,
        sha256(args.quest_sql),
        sha256(args.area_dbc),
    )
    if args.check:
        if args.output.read_text(encoding="utf-8") != output:
            raise SystemExit("generated quest reward data is out of date")
    else:
        args.output.write_text(output, encoding="utf-8", newline="\n")

    for bucket_name in ("z1", "z2", "z3", "z4"):
        fixed = buckets[bucket_name]["fixed"]
        choice = buckets[bucket_name]["choice"]
        print(
            f"{bucket_name}: fixed={len(fixed)} choice={len(choice)} "
            f"union={len(fixed | choice)}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
